# Generated by Django 4.1.7 on 2023-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="faculty_name",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="number",
            field=models.CharField(default="number", max_length=10),
            preserve_default=False,
        ),
    ]
