# Generated by Django 4.1.7 on 2023-02-23 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_student_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                max_length=256,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
